// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Data.Context;

#nullable disable

namespace PetShop.Data.Migrations.PetShopDb
{
    [DbContext(typeof(PetShopDbContext))]
    [Migration("20260513132111_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetShop.Data.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<bool>("PodeEnfeite")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PodePerfume")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TemAlergia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoAnimal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("AnimalClienteFKIndex");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("PetShop.Data.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PetShop.Data.Models.Animal", b =>
                {
                    b.HasOne("PetShop.Data.Models.Cliente", "Cliente")
                        .WithMany("Animais")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AnimalClienteFKCnstraint");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PetShop.Data.Models.Cliente", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
